# ===========================================================================
#      https://www.gnu.org/software/autoconf-archive/ax_prog_cc_mpi.html
# ===========================================================================
#
# SYNOPSIS
#
#   AX_LINK_CMPI_TEST_FILES
#
# DESCRIPTION
#
#   This macro links the test files and scripts to the test folders
#

AC_DEFUN([AX_LINK_CMPI_TEST_FILES], [
   AC_PREREQ(2.50)
   # C-MPI testscripts
AM_COND_IF([WITH_MPI],
           [AC_CONFIG_LINKS(test/mpi/c-mpi/init_finalize-1.sh:test/mpi/testscripts/init_finalize-1.sh
                            test/mpi/c-mpi/init_finalize-2.sh:test/mpi/testscripts/init_finalize-2.sh
                            test/mpi/c-mpi/init_finalize-3.sh:test/mpi/testscripts/init_finalize-3.sh
                            test/mpi/c-mpi/init_finalize-4.sh:test/mpi/testscripts/init_finalize-4.sh
                            test/mpi/c-mpi/ctypes.sh:test/mpi/testscripts/ctypes.sh
                            test/mpi/c-mpi/derived_ctypes.sh:test/mpi/testscripts/derived_ctypes.sh
                            test/mpi/c-mpi/pcontrol.sh:test/mpi/testscripts/pcontrol.sh
                            test/mpi/c-mpi/send_recv.sh:test/mpi/testscripts/send_recv.sh
                            test/mpi/c-mpi/isend_recv.sh:test/mpi/testscripts/isend_recv.sh
                            test/mpi/c-mpi/bsend_recv.sh:test/mpi/testscripts/bsend_recv.sh
                            test/mpi/c-mpi/ibsend_recv.sh:test/mpi/testscripts/ibsend_recv.sh
                            test/mpi/c-mpi/ssend_recv.sh:test/mpi/testscripts/ssend_recv.sh
                            test/mpi/c-mpi/issend_recv.sh:test/mpi/testscripts/issend_recv.sh
                            test/mpi/c-mpi/rsend_recv.sh:test/mpi/testscripts/rsend_recv.sh
                            test/mpi/c-mpi/irsend_recv.sh:test/mpi/testscripts/irsend_recv.sh
                            test/mpi/c-mpi/send_irecv.sh:test/mpi/testscripts/send_irecv.sh
                            test/mpi/c-mpi/sendrecv.sh:test/mpi/testscripts/sendrecv.sh
                            test/mpi/c-mpi/sendrecv_replace.sh:test/mpi/testscripts/sendrecv_replace.sh
                            test/mpi/c-mpi/probe.sh:test/mpi/testscripts/probe.sh
                            test/mpi/c-mpi/iprobe.sh:test/mpi/testscripts/iprobe.sh
                            test/mpi/c-mpi/start.sh:test/mpi/testscripts/start.sh
                            test/mpi/c-mpi/startall.sh:test/mpi/testscripts/startall.sh
                            test/mpi/c-mpi/send_init.sh:test/mpi/testscripts/send_init.sh
                            test/mpi/c-mpi/bsend_init.sh:test/mpi/testscripts/bsend_init.sh
                            test/mpi/c-mpi/ssend_init.sh:test/mpi/testscripts/ssend_init.sh
                            test/mpi/c-mpi/rsend_init.sh:test/mpi/testscripts/rsend_init.sh
                            test/mpi/c-mpi/recv_init.sh:test/mpi/testscripts/recv_init.sh
                            test/mpi/c-mpi/barrier.sh:test/mpi/testscripts/barrier.sh
                            test/mpi/c-mpi/bcast.sh:test/mpi/testscripts/bcast.sh
                            test/mpi/c-mpi/bcast_intercom.sh:test/mpi/testscripts/bcast_intercom.sh
                            test/mpi/c-mpi/ibcast.sh:test/mpi/testscripts/ibcast.sh
                            test/mpi/c-mpi/ibcast_intercom.sh:test/mpi/testscripts/ibcast_intercom.sh
                            test/mpi/c-mpi/gather.sh:test/mpi/testscripts/gather.sh
                            test/mpi/c-mpi/gather_intercom.sh:test/mpi/testscripts/gather_intercom.sh
                            test/mpi/c-mpi/gather_inplace.sh:test/mpi/testscripts/gather_inplace.sh
                            test/mpi/c-mpi/igather.sh:test/mpi/testscripts/igather.sh
                            test/mpi/c-mpi/igather_intercom.sh:test/mpi/testscripts/igather_intercom.sh
                            test/mpi/c-mpi/igather_inplace.sh:test/mpi/testscripts/igather_inplace.sh
                            test/mpi/c-mpi/gatherv.sh:test/mpi/testscripts/gatherv.sh
                            test/mpi/c-mpi/gatherv_intercom.sh:test/mpi/testscripts/gatherv_intercom.sh
                            test/mpi/c-mpi/gatherv_inplace.sh:test/mpi/testscripts/gatherv_inplace.sh
                            test/mpi/c-mpi/igatherv.sh:test/mpi/testscripts/igatherv.sh
                            test/mpi/c-mpi/igatherv_intercom.sh:test/mpi/testscripts/igatherv_intercom.sh
                            test/mpi/c-mpi/igatherv_inplace.sh:test/mpi/testscripts/igatherv_inplace.sh
                            test/mpi/c-mpi/scatter.sh:test/mpi/testscripts/scatter.sh
                            test/mpi/c-mpi/scatter_intercom.sh:test/mpi/testscripts/scatter_intercom.sh
                            test/mpi/c-mpi/scatter_inplace.sh:test/mpi/testscripts/scatter_inplace.sh
                            test/mpi/c-mpi/iscatter.sh:test/mpi/testscripts/iscatter.sh
                            test/mpi/c-mpi/iscatter_intercom.sh:test/mpi/testscripts/iscatter_intercom.sh
                            test/mpi/c-mpi/iscatter_inplace.sh:test/mpi/testscripts/iscatter_inplace.sh
                            test/mpi/c-mpi/scatterv.sh:test/mpi/testscripts/scatterv.sh
                            test/mpi/c-mpi/scatterv_intercom.sh:test/mpi/testscripts/scatterv_intercom.sh
                            test/mpi/c-mpi/scatterv_inplace.sh:test/mpi/testscripts/scatterv_inplace.sh
                            test/mpi/c-mpi/iscatterv.sh:test/mpi/testscripts/iscatterv.sh
                            test/mpi/c-mpi/iscatterv_intercom.sh:test/mpi/testscripts/iscatterv_intercom.sh
                            test/mpi/c-mpi/iscatterv_inplace.sh:test/mpi/testscripts/iscatterv_inplace.sh
                            test/mpi/c-mpi/allgather.sh:test/mpi/testscripts/allgather.sh
                            test/mpi/c-mpi/allgather_intercom.sh:test/mpi/testscripts/allgather_intercom.sh
                            test/mpi/c-mpi/allgather_inplace.sh:test/mpi/testscripts/allgather_inplace.sh
                            test/mpi/c-mpi/iallgather.sh:test/mpi/testscripts/iallgather.sh
                            test/mpi/c-mpi/iallgather_intercom.sh:test/mpi/testscripts/iallgather_intercom.sh
                            test/mpi/c-mpi/iallgather_inplace.sh:test/mpi/testscripts/iallgather_inplace.sh
                            test/mpi/c-mpi/allgatherv.sh:test/mpi/testscripts/allgatherv.sh
                            test/mpi/c-mpi/allgatherv_intercom.sh:test/mpi/testscripts/allgatherv_intercom.sh
                            test/mpi/c-mpi/allgatherv_inplace.sh:test/mpi/testscripts/allgatherv_inplace.sh
                            test/mpi/c-mpi/iallgatherv.sh:test/mpi/testscripts/iallgatherv.sh
                            test/mpi/c-mpi/iallgatherv_intercom.sh:test/mpi/testscripts/iallgatherv_intercom.sh
                            test/mpi/c-mpi/iallgatherv_inplace.sh:test/mpi/testscripts/iallgatherv_inplace.sh
                            test/mpi/c-mpi/alltoall.sh:test/mpi/testscripts/alltoall.sh
                            test/mpi/c-mpi/alltoall_intercom.sh:test/mpi/testscripts/alltoall_intercom.sh
                            test/mpi/c-mpi/alltoall_inplace.sh:test/mpi/testscripts/alltoall_inplace.sh
                            test/mpi/c-mpi/ialltoall.sh:test/mpi/testscripts/ialltoall.sh
                            test/mpi/c-mpi/ialltoall_intercom.sh:test/mpi/testscripts/ialltoall_intercom.sh
                            test/mpi/c-mpi/ialltoall_inplace.sh:test/mpi/testscripts/ialltoall_inplace.sh
                            test/mpi/c-mpi/alltoallv.sh:test/mpi/testscripts/alltoallv.sh
                            test/mpi/c-mpi/alltoallv_intercom.sh:test/mpi/testscripts/alltoallv_intercom.sh
                            test/mpi/c-mpi/alltoallv_inplace.sh:test/mpi/testscripts/alltoallv_inplace.sh
                            test/mpi/c-mpi/ialltoallv.sh:test/mpi/testscripts/ialltoallv.sh
                            test/mpi/c-mpi/ialltoallv_intercom.sh:test/mpi/testscripts/ialltoallv_intercom.sh
                            test/mpi/c-mpi/ialltoallv_inplace.sh:test/mpi/testscripts/ialltoallv_inplace.sh
                            test/mpi/c-mpi/alltoallw.sh:test/mpi/testscripts/alltoallw.sh
                            test/mpi/c-mpi/alltoallw_intercom.sh:test/mpi/testscripts/alltoallw_intercom.sh
                            test/mpi/c-mpi/alltoallw_inplace.sh:test/mpi/testscripts/alltoallw_inplace.sh
                            test/mpi/c-mpi/ialltoallw.sh:test/mpi/testscripts/ialltoallw.sh
                            test/mpi/c-mpi/ialltoallw_intercom.sh:test/mpi/testscripts/ialltoallw_intercom.sh
                            test/mpi/c-mpi/ialltoallw_inplace.sh:test/mpi/testscripts/ialltoallw_inplace.sh
                            test/mpi/c-mpi/reduce.sh:test/mpi/testscripts/reduce.sh
                            test/mpi/c-mpi/reduce_intercom.sh:test/mpi/testscripts/reduce_intercom.sh
                            test/mpi/c-mpi/reduce_inplace.sh:test/mpi/testscripts/reduce_inplace.sh
                            test/mpi/c-mpi/ireduce.sh:test/mpi/testscripts/ireduce.sh
                            test/mpi/c-mpi/ireduce_intercom.sh:test/mpi/testscripts/ireduce_intercom.sh
                            test/mpi/c-mpi/ireduce_inplace.sh:test/mpi/testscripts/ireduce_inplace.sh
                            test/mpi/c-mpi/allreduce.sh:test/mpi/testscripts/allreduce.sh
                            test/mpi/c-mpi/allreduce_intercom.sh:test/mpi/testscripts/allreduce_intercom.sh
                            test/mpi/c-mpi/allreduce_inplace.sh:test/mpi/testscripts/allreduce_inplace.sh
                            test/mpi/c-mpi/iallreduce.sh:test/mpi/testscripts/iallreduce.sh
                            test/mpi/c-mpi/iallreduce_intercom.sh:test/mpi/testscripts/iallreduce_intercom.sh
                            test/mpi/c-mpi/iallreduce_inplace.sh:test/mpi/testscripts/iallreduce_inplace.sh
                            test/mpi/c-mpi/reduce_scatter_block.sh:test/mpi/testscripts/reduce_scatter_block.sh
                            test/mpi/c-mpi/reduce_scatter_block_intercom.sh:test/mpi/testscripts/reduce_scatter_block_intercom.sh
                            test/mpi/c-mpi/reduce_scatter_block_inplace.sh:test/mpi/testscripts/reduce_scatter_block_inplace.sh
                            test/mpi/c-mpi/ireduce_scatter_block.sh:test/mpi/testscripts/ireduce_scatter_block.sh
                            test/mpi/c-mpi/ireduce_scatter_block_intercom.sh:test/mpi/testscripts/ireduce_scatter_block_intercom.sh
                            test/mpi/c-mpi/ireduce_scatter_block_inplace.sh:test/mpi/testscripts/ireduce_scatter_block_inplace.sh
                            test/mpi/c-mpi/reduce_scatter.sh:test/mpi/testscripts/reduce_scatter.sh
                            test/mpi/c-mpi/reduce_scatter_intercom.sh:test/mpi/testscripts/reduce_scatter_intercom.sh
                            test/mpi/c-mpi/reduce_scatter_inplace.sh:test/mpi/testscripts/reduce_scatter_inplace.sh
                            test/mpi/c-mpi/ireduce_scatter.sh:test/mpi/testscripts/ireduce_scatter.sh
                            test/mpi/c-mpi/ireduce_scatter_intercom.sh:test/mpi/testscripts/ireduce_scatter_intercom.sh
                            test/mpi/c-mpi/ireduce_scatter_inplace.sh:test/mpi/testscripts/ireduce_scatter_inplace.sh
                            test/mpi/c-mpi/scan.sh:test/mpi/testscripts/scan.sh
                            test/mpi/c-mpi/scan_inplace.sh:test/mpi/testscripts/scan_inplace.sh
                            test/mpi/c-mpi/iscan.sh:test/mpi/testscripts/iscan.sh
                            test/mpi/c-mpi/iscan_inplace.sh:test/mpi/testscripts/iscan_inplace.sh
                            test/mpi/c-mpi/exscan.sh:test/mpi/testscripts/exscan.sh
                            test/mpi/c-mpi/exscan_inplace.sh:test/mpi/testscripts/exscan_inplace.sh
                            test/mpi/c-mpi/iexscan.sh:test/mpi/testscripts/iexscan.sh
                            test/mpi/c-mpi/iexscan_inplace.sh:test/mpi/testscripts/iexscan_inplace.sh
                            test/mpi/c-mpi/put.sh:test/mpi/testscripts/put.sh
                            test/mpi/c-mpi/rput.sh:test/mpi/testscripts/rput.sh
                            test/mpi/c-mpi/get.sh:test/mpi/testscripts/get.sh
                            test/mpi/c-mpi/rget.sh:test/mpi/testscripts/rget.sh
                            test/mpi/c-mpi/accumulate.sh:test/mpi/testscripts/accumulate.sh
                            test/mpi/c-mpi/raccumulate.sh:test/mpi/testscripts/raccumulate.sh
                            test/mpi/c-mpi/get_accumulate.sh:test/mpi/testscripts/get_accumulate.sh
                            test/mpi/c-mpi/rget_accumulate.sh:test/mpi/testscripts/rget_accumulate.sh
                            test/mpi/c-mpi/fetch_and_op.sh:test/mpi/testscripts/fetch_and_op.sh
                            test/mpi/c-mpi/compare_and_swap.sh:test/mpi/testscripts/compare_and_swap.sh
                            test/mpi/c-mpi/test.sh:test/mpi/testscripts/test.sh
                            test/mpi/c-mpi/testany.sh:test/mpi/testscripts/testany.sh
                            test/mpi/c-mpi/testsome.sh:test/mpi/testscripts/testsome.sh
                            test/mpi/c-mpi/testall.sh:test/mpi/testscripts/testall.sh
                            test/mpi/c-mpi/wait.sh:test/mpi/testscripts/wait.sh
                            test/mpi/c-mpi/waitany.sh:test/mpi/testscripts/waitany.sh
                            test/mpi/c-mpi/waitsome.sh:test/mpi/testscripts/waitsome.sh
                            test/mpi/c-mpi/waitall.sh:test/mpi/testscripts/waitall.sh
                           )
           ])

])
