MODULE vftr_mpi_put_f2vftr_fi
#ifdef _MPI

   USE, INTRINSIC :: ISO_FORTRAN_ENV
   USE, INTRINSIC :: ISO_C_BINDING

   IMPLICIT NONE

   PRIVATE

   PUBLIC :: vftr_MPI_Put_f2vftr

   INTERFACE

      SUBROUTINE vftr_MPI_Put_f2vftr(ORIGIN_ADDR, ORIGIN_COUNT, F_ORIGIN_DATATYPE, &
                                  TARGET_RANK, TARGET_DISP, TARGET_COUNT, &
                                  F_TARGET_DATATYPE, F_WIN, F_ERROR) &
         BIND(C, name="vftr_MPI_Put_f2vftr")
         USE mpi, ONLY: MPI_ADDRESS_KIND
         IMPLICIT NONE
         INTEGER ORIGIN_ADDR
         INTEGER ORIGIN_COUNT
         INTEGER F_ORIGIN_DATATYPE
         INTEGER TARGET_RANK
         INTEGER(KIND=MPI_ADDRESS_KIND) TARGET_DISP
         INTEGER TARGET_COUNT
         INTEGER F_TARGET_DATATYPE
         INTEGER F_WIN
         INTEGER F_ERROR
      END SUBROUTINE vftr_MPI_Put_f2vftr

   END INTERFACE

#endif

CONTAINS

END MODULE vftr_mpi_put_f2vftr_fi
