#ifdef _MPI

SUBROUTINE MPI_IRECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, REQUEST, ERROR)
   USE vftr_mpi_irecv_f2vftr_fi, &
      ONLY : vftr_MPI_Irecv_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY : PMPI_IRECV
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER SOURCE
   INTEGER TAG
   INTEGER COMM
   INTEGER REQUEST
   INTEGER ERROR

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_IRECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, REQUEST, ERROR)
   ELSE
      CALL vftr_MPI_Irecv_f2vftr(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, REQUEST, ERROR)
   END IF

END SUBROUTINE MPI_IRECV

#endif
