#ifdef _MPI

SUBROUTINE MPI_ISEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)
   USE vftr_mpi_isend_f2vftr_fi, &
      ONLY : vftr_MPI_Isend_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY : PMPI_ISEND
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER REQUEST
   INTEGER ERROR

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_ISEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)
   ELSE
      CALL vftr_MPI_Isend_f2vftr(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)
   END IF

END SUBROUTINE MPI_ISEND

#endif
