#ifdef _MPI

SUBROUTINE MPI_RECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, ERROR)
   USE vftr_mpi_recv_f2vftr_fi, &
      ONLY : vftr_MPI_Recv_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY : PMPI_RECV, &
             MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER SOURCE
   INTEGER TAG
   INTEGER COMM
   INTEGER STATUS(MPI_STATUS_SIZE)
   INTEGER ERROR

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_RECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, ERROR)
   ELSE
      CALL vftr_MPI_Recv_f2vftr(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, ERROR)
   END IF

END SUBROUTINE MPI_RECV

#endif
