#ifdef _MPI

SUBROUTINE MPI_RPUT(ORIGIN_ADDR, ORIGIN_COUNT, ORIGIN_DATATYPE, &
                    TARGET_RANK, TARGET_DISP, TARGET_COUNT, &
                    TARGET_DATATYPE, WIN, REQUEST, ERROR)
   USE vftr_mpi_rput_f2vftr_fi, &
      ONLY : vftr_MPI_Rput_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY: PMPI_RPUT, &
            MPI_ADDRESS_KIND
   IMPLICIT NONE
   INTEGER ORIGIN_ADDR
   INTEGER ORIGIN_COUNT
   INTEGER ORIGIN_DATATYPE
   INTEGER TARGET_RANK
   INTEGER(KIND=MPI_ADDRESS_KIND) TARGET_DISP
   INTEGER TARGET_COUNT
   INTEGER TARGET_DATATYPE
   INTEGER WIN
   INTEGER REQUEST
   INTEGER ERROR

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_RPUT(ORIGIN_ADDR, ORIGIN_COUNT, ORIGIN_DATATYPE, &
                     TARGET_RANK, TARGET_DISP, TARGET_COUNT, &
                     TARGET_DATATYPE, WIN, REQUEST, ERROR)
   ELSE
      CALL vftr_MPI_Rput_f2vftr(ORIGIN_ADDR, ORIGIN_COUNT, ORIGIN_DATATYPE, &
                             TARGET_RANK, TARGET_DISP, TARGET_COUNT, &
                             TARGET_DATATYPE, WIN, REQUEST, ERROR)
   END IF

END SUBROUTINE MPI_RPUT

#endif
