#ifdef _MPI

SUBROUTINE MPI_SENDRECV(SENDBUF, SENDCOUNT, SENDTYPE, DEST, SENDTAG, &
                        RECVBUF, RECVCOUNT, RECVTYPE, SOURCE, RECVTAG, &
                        COMM, STATUS, ERROR)
   USE vftr_mpi_sendrecv_f2vftr_fi, &
      ONLY : vftr_MPI_Sendrecv_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY : PMPI_SENDRECV, &
             MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER SENDBUF
   INTEGER SENDCOUNT
   INTEGER SENDTYPE
   INTEGER DEST
   INTEGER SENDTAG
   INTEGER RECVBUF
   INTEGER RECVCOUNT
   INTEGER RECVTYPE
   INTEGER SOURCE
   INTEGER RECVTAG
   INTEGER COMM
   INTEGER STATUS(MPI_STATUS_SIZE)
   INTEGER ERROR

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_SENDRECV(SENDBUF, SENDCOUNT, SENDTYPE, DEST, SENDTAG, &
                         RECVBUF, RECVCOUNT, RECVTYPE, SOURCE, RECVTAG, &
                         COMM, STATUS, ERROR)
   ELSE
      CALL vftr_MPI_Sendrecv_f2vftr(SENDBUF, SENDCOUNT, SENDTYPE, DEST, SENDTAG, &
                                 RECVBUF, RECVCOUNT, RECVTYPE, SOURCE, RECVTAG, &
                                 COMM, STATUS, ERROR)
   END IF

END SUBROUTINE MPI_SENDRECV

#endif
