#ifdef _MPI

SUBROUTINE MPI_TESTALL(COUNT, ARRAY_OREQUESTS, FLAG, ARRAY_OSTATUSES, ERROR)
   USE vftr_mpi_testall_f2vftr_fi, &
      ONLY : vftr_MPI_Testall_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY: PMPI_TESTALL, &
            MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER COUNT
   INTEGER ARRAY_OREQUESTS(*)
   LOGICAL FLAG
   INTEGER ARRAY_OSTATUSES(MPI_STATUS_SIZE,*)
   INTEGER ERROR

   INTEGER TMPFLAG

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_TESTALL(COUNT, ARRAY_OREQUESTS, FLAG, ARRAY_OSTATUSES, ERROR)
   ELSE
      CALL vftr_MPI_Testall_f2vftr(COUNT, ARRAY_OREQUESTS, TMPFLAG, ARRAY_OSTATUSES, ERROR)

      FLAG = (TMPFLAG /= 0)
   END IF

END SUBROUTINE MPI_TESTALL

#endif
