#ifdef _MPI

SUBROUTINE MPI_TESTSOME(INCOUNT, ARRAY_OREQUESTS, OUTCOUNT, &
                        ARRAY_OINDICES, ARRAY_OSTATUSES, ERROR)
   USE vftr_mpi_testsome_f2vftr_fi, &
      ONLY : vftr_MPI_Testsome_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY: PMPI_TESTSOME, &
            MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER INCOUNT
   INTEGER ARRAY_OREQUESTS(*)
   INTEGER OUTCOUNT
   INTEGER ARRAY_OINDICES(*)
   INTEGER ARRAY_OSTATUSES(MPI_STATUS_SIZE,*)
   INTEGER ERROR

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_TESTSOME(INCOUNT, ARRAY_OREQUESTS, OUTCOUNT, &
                         ARRAY_OINDICES, ARRAY_OSTATUSES, ERROR)
   ELSE
      CALL vftr_MPI_Testsome_f2vftr(INCOUNT, ARRAY_OREQUESTS, OUTCOUNT, &
                                 ARRAY_OINDICES, ARRAY_OSTATUSES, ERROR)
   END IF

END SUBROUTINE MPI_TESTSOME

#endif
