#ifdef _MPI

SUBROUTINE MPI_TESTANY(COUNT, ARRAY_OREQUESTS, INDEX, FLAG, STATUS, ERROR)
   USE vftr_mpi_testany_f2vftr_fi, &
      ONLY : vftr_MPI_Testany_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY: PMPI_TESTANY, &
            MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER COUNT
   INTEGER ARRAY_OREQUESTS(*)
   INTEGER INDEX
   LOGICAL FLAG
   INTEGER STATUS(MPI_STATUS_SIZE)
   INTEGER ERROR
   INTEGER TMPFLAG

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_TESTANY(COUNT, ARRAY_OREQUESTS, INDEX, FLAG, STATUS, ERROR)
   ELSE
      CALL vftr_MPI_Testany_f2vftr(COUNT, ARRAY_OREQUESTS, INDEX, TMPFLAG, STATUS, ERROR)

      FLAG = (TMPFLAG /= 0)
   END IF

END SUBROUTINE MPI_TESTANY

#endif
