#ifdef _MPI

SUBROUTINE MPI_WAITANY(COUNT, ARRAY_OREQUESTS, INDEX, STATUS, ERROR)
   USE vftr_mpi_waitany_f2vftr_fi, &
      ONLY : vftr_MPI_Waitany_f2vftr
   USE vftr_mpi_logging_F, &
      ONLY : vftr_no_mpi_logging_F
   USE mpi, &
      ONLY: PMPI_WAITANY, &
            MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER COUNT
   INTEGER ARRAY_OREQUESTS(*)
   INTEGER INDEX
   INTEGER STATUS(MPI_STATUS_SIZE)
   INTEGER ERROR

   IF (vftr_no_mpi_logging_F()) THEN
      CALL PMPI_WAITANY(COUNT, ARRAY_OREQUESTS, INDEX, STATUS, ERROR)
   ELSE
      CALL vftr_MPI_Waitany_f2vftr(COUNT, ARRAY_OREQUESTS, INDEX, STATUS, ERROR)
   END IF

END SUBROUTINE MPI_WAITANY

#endif

