.TH VFTRACE_CHECK_CONFIG "1" "MONTH YEAR" "Vftrace VERSION" "VFTRACE"
.SH NAME
vftrace_check_config
.SH SYNOPSIS
\fBvftrace_check_config\fR config.json

.SH DESCRIPTION
.\" Add any additional description here
.PP
\fBvftrace_check_config\fR takes the vftrace config file in JSON format
and checks it for compatibility with vftrace. It will parse the config, like vftrace does during runtime.
Every given path will be checked for existence and permissions.
The ranges will be expanded and checked for validity.
All regular expressions will be compiled.
At last vftrace_check_config will go through every element in your config file
and check if it corresponds to a valid vftrace option. This way it can spot typos and will suggest
corrections.
