! This file is part of Vftrace.
!
! Vftrace is free software; you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation; either version 2 of the License, or
! (at your option) any later version.
!
! Vftrace is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License along
! with this program; if not, write to the Free Software Foundation, Inc.,
! 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#ifdef _MPI

SUBROUTINE MPI_SEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Send_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER ERROR

   CALL vftr_MPI_Send_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, ERROR)

END SUBROUTINE MPI_SEND

SUBROUTINE MPI_BSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Bsend_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER ERROR

   CALL vftr_MPI_Bsend_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, ERROR)

END SUBROUTINE MPI_BSEND

SUBROUTINE MPI_BSEND_INIT(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Bsend_init_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER REQUEST
   INTEGER ERROR

   CALL vftr_MPI_Bsend_init_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)

END SUBROUTINE MPI_BSEND_INIT

SUBROUTINE MPI_ISEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Isend_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER REQUEST
   INTEGER ERROR

   CALL vftr_MPI_Isend_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)

END SUBROUTINE MPI_ISEND

SUBROUTINE MPI_IBSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Ibsend_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER REQUEST
   INTEGER ERROR

   CALL vftr_MPI_Ibsend_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)

END SUBROUTINE MPI_IBSEND

SUBROUTINE MPI_SSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Ssend_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER ERROR

   CALL vftr_MPI_Ssend_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, ERROR)

END SUBROUTINE MPI_SSEND

SUBROUTINE MPI_ISSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Issend_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER REQUEST
   INTEGER ERROR

   CALL vftr_MPI_Issend_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)

END SUBROUTINE MPI_ISSEND

SUBROUTINE MPI_RSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Rsend_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER ERROR

   CALL vftr_MPI_Rsend_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, ERROR)

END SUBROUTINE MPI_RSEND

SUBROUTINE MPI_IRSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Irsend_F
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER TAG
   INTEGER COMM
   INTEGER REQUEST
   INTEGER ERROR

   CALL vftr_MPI_Irsend_F(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, ERROR)

END SUBROUTINE MPI_IRSEND

SUBROUTINE MPI_RECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Recv_F
   USE mpi, ONLY : MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER SOURCE
   INTEGER TAG
   INTEGER COMM
   INTEGER STATUS(MPI_STATUS_SIZE)
   INTEGER ERROR

   CALL vftr_MPI_Recv_F(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, ERROR)

END SUBROUTINE MPI_RECV

SUBROUTINE MPI_IRECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, REQUEST, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Irecv_F
   USE mpi, ONLY : MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER SOURCE
   INTEGER TAG
   INTEGER COMM
   INTEGER STATUS(MPI_STATUS_SIZE)
   INTEGER REQUEST
   INTEGER ERROR

   CALL vftr_MPI_Irecv_F(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, REQUEST, ERROR)
   
END SUBROUTINE MPI_IRECV

SUBROUTINE MPI_SENDRECV(SENDBUF, SENDCOUNT, SENDTYPE, DEST, SENDTAG, &
                        RECVBUF, RECVCOUNT, RECVTYPE, SOURCE, RECVTAG, &
                        COMM, STATUS, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Sendrecv_F
   USE mpi, ONLY : MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER SENDBUF
   INTEGER SENDCOUNT
   INTEGER SENDTYPE
   INTEGER DEST
   INTEGER SENDTAG
   INTEGER RECVBUF
   INTEGER RECVCOUNT
   INTEGER RECVTYPE
   INTEGER SOURCE
   INTEGER RECVTAG
   INTEGER COMM
   INTEGER STATUS(MPI_STATUS_SIZE)
   INTEGER ERROR

   CALL vftr_MPI_Sendrecv_F(SENDBUF, SENDCOUNT, SENDTYPE, DEST, SENDTAG, &
                            RECVBUF, RECVCOUNT, RECVTYPE, SOURCE, RECVTAG, &
                            COMM, STATUS, ERROR)

END SUBROUTINE MPI_SENDRECV

SUBROUTINE MPI_SENDRECV_REPLACE(BUF, COUNT, DATATYPE, DEST, SENDTAG, SOURCE, &
                                RECVTAG, COMM, STATUS, ERROR)
   USE vftr_mpi_point2point_c2F, &
      ONLY : vftr_MPI_Sendrecv_replace_F
   USE mpi, ONLY : MPI_STATUS_SIZE
   IMPLICIT NONE
   INTEGER BUF
   INTEGER COUNT
   INTEGER DATATYPE
   INTEGER DEST
   INTEGER SENDTAG
   INTEGER SOURCE
   INTEGER RECVTAG
   INTEGER COMM
   INTEGER STATUS(MPI_STATUS_SIZE)
   INTEGER ERROR

   CALL vftr_MPI_Sendrecv_replace_F(BUF, COUNT, DATATYPE, DEST, SENDTAG, SOURCE, &
                                    RECVTAG, COMM, STATUS, ERROR)

END SUBROUTINE MPI_SENDRECV_REPLACE

#endif
